# Apply the kFdChunk C++11 ODR out-of-class definition to a populated MNN tree.
# Does not change MNN commit, backend flags, or -std. Does not call patch(1).
#
# Script mode:
#   cmake -P apply_kFdChunk_odr.cmake -- <MNN_SOURCE_DIR>
# Include mode (MNN_SOURCE_DIR already set by operit_prepare_git_source):
#   include("${path}/apply_kFdChunk_odr.cmake")

if(CMAKE_SCRIPT_MODE_FILE AND CMAKE_SCRIPT_MODE_FILE STREQUAL CMAKE_CURRENT_LIST_FILE)
  cmake_minimum_required(VERSION 3.18)
endif()

function(_mnn_kfdchunk_load_hashes hash_file)
  if(NOT EXISTS "${hash_file}")
    message(FATAL_ERROR "mnn-link-fix: refuse: missing ${hash_file}")
  endif()
  set(_hpp_unpatched "")
  set(_hpp_patched "")
  set(_cpp_unpatched "")
  set(_cpp_patched "")
  file(STRINGS "${hash_file}" _lines)
  foreach(_line IN LISTS _lines)
    string(REPLACE "\r" "" _line "${_line}")
    if(_line MATCHES "^([a-z_]+)=([0-9a-fA-F]+)$")
      set(_${CMAKE_MATCH_1} "${CMAKE_MATCH_2}")
    endif()
  endforeach()
  foreach(_req hpp_unpatched hpp_patched cpp_unpatched cpp_patched)
    if(NOT _${_req})
      message(FATAL_ERROR "mnn-link-fix: refuse: ${hash_file} missing ${_req}")
    endif()
  endforeach()
  string(TOLOWER "${_hpp_unpatched}" _hpp_unpatched)
  string(TOLOWER "${_hpp_patched}" _hpp_patched)
  string(TOLOWER "${_cpp_unpatched}" _cpp_unpatched)
  string(TOLOWER "${_cpp_patched}" _cpp_patched)
  set(hpp_unpatched "${_hpp_unpatched}" PARENT_SCOPE)
  set(hpp_patched "${_hpp_patched}" PARENT_SCOPE)
  set(cpp_unpatched "${_cpp_unpatched}" PARENT_SCOPE)
  set(cpp_patched "${_cpp_patched}" PARENT_SCOPE)
endfunction()

function(_mnn_kfdchunk_parse_script_args out_var)
  set(_result "")
  set(_after_script FALSE)
  math(EXPR _n "${CMAKE_ARGC} - 1")
  foreach(_i RANGE 0 ${_n})
    set(_a "${CMAKE_ARGV${_i}}")
    if(_after_script)
      if(NOT _a STREQUAL "--")
        list(APPEND _result "${_a}")
      endif()
    elseif(CMAKE_SCRIPT_MODE_FILE AND _a STREQUAL "${CMAKE_SCRIPT_MODE_FILE}")
      set(_after_script TRUE)
    endif()
  endforeach()
  set(${out_var} "${_result}" PARENT_SCOPE)
endfunction()

function(mnn_link_fix_apply_kfdchunk source_dir)
  if(NOT source_dir)
    message(FATAL_ERROR "mnn-link-fix: refuse: usage: cmake -P apply_kFdChunk_odr.cmake -- <MNN_SOURCE_DIR>")
  endif()
  get_filename_component(source_dir "${source_dir}" ABSOLUTE)
  set(_portable_dir "${CMAKE_CURRENT_FUNCTION_LIST_DIR}")
  set(_hash_file "${_portable_dir}/expected-sha256.txt")
  set(_rel_hpp "source/backend/opencl/execution/buffer/AttentionBufExecution.hpp")
  set(_rel_cpp "source/backend/opencl/execution/buffer/AttentionBufExecution.cpp")
  set(_hpp "${source_dir}/${_rel_hpp}")
  set(_cpp "${source_dir}/${_rel_cpp}")
  set(_def_line "constexpr int AttentionBufExecution::kFdChunk;")
  set(_anchor [=[#include <fstream>
namespace MNN {
namespace OpenCL {

// Which prefill implementation onResize picks. Persisted in the tune cache, so the
]=])
  set(_repl [=[#include <fstream>
namespace MNN {
namespace OpenCL {

constexpr int AttentionBufExecution::kFdChunk;

// Which prefill implementation onResize picks. Persisted in the tune cache, so the
]=])

  _mnn_kfdchunk_load_hashes("${_hash_file}")
  if(NOT EXISTS "${_hpp}")
    message(FATAL_ERROR "mnn-link-fix: refuse: missing ${_hpp}")
  endif()
  if(NOT EXISTS "${_cpp}")
    message(FATAL_ERROR "mnn-link-fix: refuse: missing ${_cpp}")
  endif()

  file(SHA256 "${_hpp}" _hpp_sha)
  file(SHA256 "${_cpp}" _cpp_sha)
  string(TOLOWER "${_hpp_sha}" _hpp_sha)
  string(TOLOWER "${_cpp_sha}" _cpp_sha)

  if(NOT _hpp_sha STREQUAL hpp_unpatched)
    message(FATAL_ERROR "mnn-link-fix: refuse: unknown hpp sha256=${_hpp_sha} expected ${hpp_unpatched} (${_rel_hpp})")
  endif()

  if(_cpp_sha STREQUAL cpp_patched)
    file(READ "${_cpp}" _cpp_text)
    string(FIND "${_cpp_text}" "${_def_line}" _def_pos)
    if(_def_pos EQUAL -1)
      message(FATAL_ERROR "mnn-link-fix: refuse: cpp sha matches patched but definition line missing (${_cpp})")
    endif()
    message(STATUS "mnn-link-fix: already applied; skip. cpp sha256=${_cpp_sha} path=${_cpp}")
    return()
  endif()

  if(NOT _cpp_sha STREQUAL cpp_unpatched)
    message(FATAL_ERROR "mnn-link-fix: refuse: unknown cpp sha256=${_cpp_sha} expected unpatched ${cpp_unpatched} or patched ${cpp_patched} (${_rel_cpp})")
  endif()

  file(READ "${_hpp}" _hpp_text)
  file(READ "${_cpp}" _cpp_text)
  string(SHA256 _hpp_text_sha "${_hpp_text}")
  string(SHA256 _cpp_text_sha "${_cpp_text}")
  string(TOLOWER "${_hpp_text_sha}" _hpp_text_sha)
  string(TOLOWER "${_cpp_text_sha}" _cpp_text_sha)
  if(NOT _hpp_text_sha STREQUAL _hpp_sha OR NOT _cpp_text_sha STREQUAL _cpp_sha)
    message(FATAL_ERROR "mnn-link-fix: refuse: in-memory SHA256 != file SHA256 (refusing to edit)")
  endif()

  string(FIND "${_hpp_text}" "    static constexpr int kFdChunk = 64;" _pos)
  if(_pos EQUAL -1)
    message(FATAL_ERROR "mnn-link-fix: refuse: hpp missing in-class static constexpr int kFdChunk = 64")
  endif()
  string(FIND "${_cpp_text}" "std::min(kFdChunk, (int)mMaxWorkGroupSize)" _pos)
  if(_pos EQUAL -1)
    message(FATAL_ERROR "mnn-link-fix: refuse: cpp missing flashDecodeResize std::min(kFdChunk, ...) ODR-use")
  endif()
  string(FIND "${_cpp_text}" "std::min(kFdChunk, static_cast<int>(mMaxWorkGroupSize))" _pos)
  if(_pos EQUAL -1)
    message(FATAL_ERROR "mnn-link-fix: refuse: cpp missing prebuildOpenCLPrograms std::min(kFdChunk, ...) ODR-use")
  endif()
  string(FIND "${_cpp_text}" "${_def_line}" _pos)
  if(NOT _pos EQUAL -1)
    message(FATAL_ERROR "mnn-link-fix: refuse: unpatched sha but definition line already present (${_cpp})")
  endif()

  string(FIND "${_cpp_text}" "${_anchor}" _anchor_pos)
  if(_anchor_pos EQUAL -1)
    message(FATAL_ERROR "mnn-link-fix: refuse: cpp missing kFdChunk insert anchor")
  endif()
  string(FIND "${_cpp_text}" "${_anchor}" _anchor_pos2 REVERSE)
  if(NOT _anchor_pos EQUAL _anchor_pos2)
    message(FATAL_ERROR "mnn-link-fix: refuse: cpp insert anchor is not unique")
  endif()

  string(REPLACE "${_anchor}" "${_repl}" _new_cpp "${_cpp_text}")
  if(_new_cpp STREQUAL _cpp_text)
    message(FATAL_ERROR "mnn-link-fix: refuse: insert produced no change")
  endif()
  string(FIND "${_new_cpp}" "${_def_line}" _pos)
  if(_pos EQUAL -1)
    message(FATAL_ERROR "mnn-link-fix: refuse: insert missed definition line")
  endif()

  string(SHA256 _new_sha "${_new_cpp}")
  string(TOLOWER "${_new_sha}" _new_sha)
  if(NOT _new_sha STREQUAL cpp_patched)
    message(FATAL_ERROR "mnn-link-fix: refuse: in-memory patch sha256=${_new_sha} expected ${cpp_patched} (source not written)")
  endif()

  set(_tmp "${_cpp}.mnn-kfdchunk.tmp")
  file(WRITE "${_tmp}" "${_new_cpp}")
  file(SHA256 "${_tmp}" _tmp_sha)
  string(TOLOWER "${_tmp_sha}" _tmp_sha)
  if(NOT _tmp_sha STREQUAL cpp_patched)
    file(REMOVE "${_tmp}")
    message(FATAL_ERROR "mnn-link-fix: refuse: temp file sha256=${_tmp_sha} expected ${cpp_patched} (source not written)")
  endif()
  file(RENAME "${_tmp}" "${_cpp}")
  file(SHA256 "${_cpp}" _after_sha)
  string(TOLOWER "${_after_sha}" _after_sha)
  if(NOT _after_sha STREQUAL cpp_patched)
    message(FATAL_ERROR "mnn-link-fix: refuse: patch produced unexpected sha256=${_after_sha} expected ${cpp_patched}")
  endif()
  message(STATUS "mnn-link-fix: applied. cpp ${cpp_unpatched} -> ${_after_sha}")
endfunction()

if(CMAKE_SCRIPT_MODE_FILE AND CMAKE_SCRIPT_MODE_FILE STREQUAL CMAKE_CURRENT_LIST_FILE)
  _mnn_kfdchunk_parse_script_args(_mnn_kfd_args)
  list(LENGTH _mnn_kfd_args _mnn_kfd_n)
  if(NOT _mnn_kfd_n EQUAL 1)
    message(FATAL_ERROR "mnn-link-fix: refuse: usage: cmake -P apply_kFdChunk_odr.cmake -- <MNN_SOURCE_DIR>")
  endif()
  list(GET _mnn_kfd_args 0 _mnn_kfd_src)
  mnn_link_fix_apply_kfdchunk("${_mnn_kfd_src}")
elseif(NOT CMAKE_SCRIPT_MODE_FILE)
  if(NOT MNN_SOURCE_DIR)
    message(FATAL_ERROR "mnn-link-fix: refuse: MNN_SOURCE_DIR is empty; include after operit_prepare_git_source")
  endif()
  mnn_link_fix_apply_kfdchunk("${MNN_SOURCE_DIR}")
endif()
