# NDK r27 and lower: both flags are required for 16 KB LOAD + GNU_RELRO.
# Official docs: -Wl,-z,max-page-size=16384 and -Wl,-z,common-page-size=16384.
# Only non-IMPORTED SHARED/MODULE targets emit an ELF we can relink.
# STATIC/OBJECT/IMPORTED/NDK prebuilts are skipped; they are not a pass.

include_guard(GLOBAL)

set(_XIAOHEI_PAGE_SIZE_MAX_FLAG "-Wl,-z,max-page-size=16384")
set(_XIAOHEI_PAGE_SIZE_COMMON_FLAG "-Wl,-z,common-page-size=16384")
set(_XIAOHEI_PAGE_SIZE_MAX_NEEDLE "max-page-size=16384")
set(_XIAOHEI_PAGE_SIZE_COMMON_NEEDLE "common-page-size=16384")

function(xiaohei_page_size_link_flags out_var)
    set(${out_var}
        "${_XIAOHEI_PAGE_SIZE_MAX_FLAG}"
        "${_XIAOHEI_PAGE_SIZE_COMMON_FLAG}"
        PARENT_SCOPE
    )
endfunction()

function(xiaohei_resolve_real_target target out_var)
    if(NOT TARGET "${target}")
        set(${out_var} "" PARENT_SCOPE)
        return()
    endif()
    get_target_property(_aliased "${target}" ALIASED_TARGET)
    if(_aliased)
        set(${out_var} "${_aliased}" PARENT_SCOPE)
    else()
        set(${out_var} "${target}" PARENT_SCOPE)
    endif()
endfunction()

function(xiaohei_target_is_relinkable_elf target out_var)
    xiaohei_resolve_real_target("${target}" _real)
    if(_real STREQUAL "")
        set(${out_var} FALSE PARENT_SCOPE)
        return()
    endif()
    get_target_property(_imported "${_real}" IMPORTED)
    if(_imported)
        set(${out_var} FALSE PARENT_SCOPE)
        return()
    endif()
    get_target_property(_type "${_real}" TYPE)
    if(_type STREQUAL "SHARED_LIBRARY" OR _type STREQUAL "MODULE_LIBRARY")
        set(${out_var} TRUE PARENT_SCOPE)
    else()
        set(${out_var} FALSE PARENT_SCOPE)
    endif()
endfunction()

function(_xiaohei_apply_16kb_page_size_one target)
    xiaohei_target_is_relinkable_elf("${target}" _ok)
    if(NOT _ok)
        return()
    endif()
    xiaohei_resolve_real_target("${target}" _real)
    # INTERFACE flags only apply to consumers; config-specific flags may not apply
    # to Release. Only unconditional PRIVATE target options count as coverage.
    get_target_property(_options "${_real}" LINK_OPTIONS)
    if(NOT _options)
        set(_options "")
    endif()
    foreach(_flag IN ITEMS "${_XIAOHEI_PAGE_SIZE_MAX_FLAG}" "${_XIAOHEI_PAGE_SIZE_COMMON_FLAG}")
        list(FIND _options "${_flag}" _index)
        if(_index EQUAL -1)
            target_link_options("${_real}" PRIVATE "${_flag}")
        endif()
    endforeach()
endfunction()

function(xiaohei_apply_16kb_page_size)
    foreach(_target IN LISTS ARGN)
        _xiaohei_apply_16kb_page_size_one("${_target}")
    endforeach()
endfunction()

function(_xiaohei_collect_link_dep_targets target out_var)
    set(_deps "")
    foreach(_prop LINK_LIBRARIES INTERFACE_LINK_LIBRARIES)
        get_target_property(_items "${target}" ${_prop})
        if(NOT _items OR _items STREQUAL "_items-NOTFOUND")
            continue()
        endif()
        foreach(_item IN LISTS _items)
            if(_item MATCHES "^\\$<LINK_ONLY:(.*)>$")
                set(_item "${CMAKE_MATCH_1}")
            endif()
            if(TARGET "${_item}")
                list(APPEND _deps "${_item}")
            endif()
        endforeach()
    endforeach()
    set(${out_var} "${_deps}" PARENT_SCOPE)
endfunction()

function(_xiaohei_apply_16kb_page_size_graph_one target)
    xiaohei_resolve_real_target("${target}" _real)
    if(_real STREQUAL "")
        return()
    endif()
    get_property(_visited GLOBAL PROPERTY _XIAOHEI_PAGE_SIZE_GRAPH_VISITED)
    list(FIND _visited "${_real}" _idx)
    if(NOT _idx EQUAL -1)
        return()
    endif()
    list(APPEND _visited "${_real}")
    set_property(GLOBAL PROPERTY _XIAOHEI_PAGE_SIZE_GRAPH_VISITED "${_visited}")

    _xiaohei_apply_16kb_page_size_one("${_real}")

    get_target_property(_imported "${_real}" IMPORTED)
    if(_imported)
        return()
    endif()

    _xiaohei_collect_link_dep_targets("${_real}" _deps)
    foreach(_dep IN LISTS _deps)
        _xiaohei_apply_16kb_page_size_graph_one("${_dep}")
    endforeach()
endfunction()

function(xiaohei_apply_16kb_page_size_graph)
    set_property(GLOBAL PROPERTY _XIAOHEI_PAGE_SIZE_GRAPH_VISITED "")
    foreach(_target IN LISTS ARGN)
        _xiaohei_apply_16kb_page_size_graph_one("${_target}")
    endforeach()
endfunction()

function(_xiaohei_apply_16kb_page_size_tree_impl dir)
    get_property(_targets DIRECTORY "${dir}" PROPERTY BUILDSYSTEM_TARGETS)
    foreach(_t IN LISTS _targets)
        _xiaohei_apply_16kb_page_size_one("${_t}")
    endforeach()
    get_property(_subs DIRECTORY "${dir}" PROPERTY SUBDIRECTORIES)
    foreach(_sd IN LISTS _subs)
        _xiaohei_apply_16kb_page_size_tree_impl("${_sd}")
    endforeach()
endfunction()

function(xiaohei_apply_16kb_page_size_tree)
    cmake_parse_arguments(ARG "" "DIRECTORY" "" ${ARGN})
    if(ARG_DIRECTORY)
        set(_root "${ARG_DIRECTORY}")
    else()
        set(_root "${CMAKE_CURRENT_SOURCE_DIR}")
    endif()
    _xiaohei_apply_16kb_page_size_tree_impl("${_root}")
endfunction()
